### ISSUE TITLE
Alt marked accepted without application

### ISSUE THREAD

**Issue by mome-borogove** [EVE-University/whctools#11]
I don't know *exactly* the steps leading up to this, but the situation ended up as:
- Main listed as on cooldown after being rejected due to skills
- WHC user panel showed Main on cooldown, all alts listed as "please apply on main"
- Reset the cooldown on Main via staff panel
- Applied on Main
- Accepted Main on staff panel
- User display shows that Main as well as one alt are both accepted as members.

I don't believe this should be possible. In fact, I'm not even sure why the main was originally listed as on cooldown due to skills, seeing as they'd been removed from the community.

Timestamps for checking logs:
- June 22, 2024, 9 p.m. WHC Community: Application Denied
```
Your application to the WHC Community on [alt1, alt2, alt3, alt4, alt5, Main, alt6, alt7, alt8, alt9] has been rejected.
	* Reason: Removed From Community
If you have any questions about this action, please contact WHC Community Coordinators on discord.
```
- June 22, 2024, 9 p.m.	WHC Community: Application Denied *(alt3 rejected...again?)*
- June 22, 2024, 9:01 p.m.	WHC application: Approved *(alt4 accepted!?)*
note: at this point, alt4 was not listed as accepted in user interface here, still says "please apply on main"
- June 23, 2024, 3:07 a.m.	WHC application availability reset *(alt6 reset)*
- June 23, 2024, 3:09 a.m.	WHC application availability reset *(main reset)*
- June 23, 2024, 3:09 a.m.	WHC application: Application Submitted *(main applied)*
- June 23, 2024, 3:09 a.m.	WHC application: Approved *(main accepted)*

It's unclear to me *what* exactly went wrong here, but *something* did. If alt4 was actually a member at 9:02pm, then the user panel was incorrectly showing it as a non-member. If alt4 was not a member at 9:02pm, then it was incorrectly accepted as a member without submitting an application after the main was accepted. Also, regardless, there should be no way that all characters were removed from the Community and then alt4 was accepted without a new application.

**Comment by lynkfox** [comment]
i think this is related to the long load period that was caused by trying to gather all the skills for all the apps all at the same time.

Ive moved the skill check window data to its own function that is only called when the button is pressed, so on the assumption that that lag was causing additional issues such as this, going to put a hold ont his issue until the new version is out and we can see if it continues

**Comment by mome-borogove** [comment]
Cannot repro this. Given the behavior of v0.2.4, I'm inclined to think that it's not possible to produce anymore. And I tried.

Considering it closed. Will reopen if we find a way to trigger it again.
