### ISSUE TITLE
Rejecting an alt for skills removes all characters

### ISSUE THREAD

**Issue by mome-borogove** [EVE-University/whctools#12]
Rejecting an alt looks like it removes all characters, including the main one.

Steps:
1. Clear everything, reset all cooldowns
2. Apply on main, accept main
3. Apply on alt 1 and alt 2
4. Reject alt 2 for skills

At this point, Main, alt 1, alt 2, and all other alts are listed as rejected for skills. All characters have been removed from the ACL and are marked as 'insufficient skills' and are on cooldown.

**Comment by mome-borogove** [comment]
Also, character re-apply cooldown looks like it may be overridden by the most recent reason. I.e., if an alt is removed for skills, all other characters are removed and the cooldown is set to the skills cooldown, regardless of whether the character was removed for a different reason.

I.e.:
1. Clear everything, reset all cooldowns
2. Apply on main, accept main
3. Apply on alts 1, 2 and 3
4. Accept 1 and 2
5. Withdraw 3
6. Remove 2 from ACL
At this point, you should see two rejected applications: alt2 with a 4 week cooldown, alt3 with a 2 day cooldown
7. Reject alt1 for skills
Now you should see four or more rejected applications, including main and alts 1, 2, and 3. All will have a 5-day skills cooldown.

**Comment by lynkfox** [comment]
Are you using the reject button or the kick button?

Reject is on Pending Applications. Kick is on accepted applications

**Comment by mome-borogove** [comment]
> Are you using the reject button or the kick button? Reject is on Pending Applications. Kick is on accepted applications

Rejecting a pending application (step 4) of an alt for skills removes any other related character, including characters that are still pending *and* characters that have already been accepted.

So to answer your question directly:
In the first example (the removal), step 4 was rejecting a pending application.
In the second example (the timers), step 6 was removing an alt via the ACL interface, then step 7 was rejecting a pending application.

**Comment by lynkfox** [comment]
Ok next question: original requirement was that only one character match for skills. ergo, if a player is being rejected for not having any toons at the minimum required skills, then none of their character should be able to be in the acl

If you are rejecting for skills on an alt, then you are in effect rejecting everyone (though I can accept that the alts probably shouldnt even have that as an option to prevent mistakes)

**Comment by mome-borogove** [comment]
You're probably right. I guess the confusion here is: if we're requiring all players to have at least one character with required skills, then there should never be a state where an alt should be able to apply without someone already having skills. That would imply a situation where there's already a main and/or more alts already accepted, but none of them have skills. The shouldn't have been there in the first place. If we're not requiring all players to have at least one character with skills, then rejecting all existing characters because of skills doesn't feel right either.

It sounds like the resolution here is either:
(a) always require one character to have skills. If at any point this is no longer true, kick all characters due to skills.
(b) allow players to remove a character with skills. I.e., if someone switches mains and doesn't have the skills, allow them to remain. In this case, rejecting an alt 'due to skills' would be like saying "listen, you used to have the skills, but you don't now, and we were nice enough to let you stay. But now you're trying to add yet more alts without skills. Stop it."

(b) seems easier, since it doesn't require a trigger. Plus, I strongly suspect (a) would need things like a grace period, discord notifications to the player, etc. to make it viable. So let's just go with that for now.

**Comment by lynkfox** [comment]
Makes sense. Will adjust

**Comment by lynkfox** [comment]
fixed in current in progress version

**Comment by mome-borogove** [comment]
Both of the issues listed here seem to be fixed in v0.2.4. Closing.
