### ISSUE TITLE
WHC applications page is slow and appears to do a lot

### ISSUE THREAD

**Issue by tremitry-darkstar** [EVE-University/whctools#14]
Some observations about the the main WHC Applications page:

- It is quite slow.
- It lists every single alt character that is linked to a main character, even if that player is applying with only one or two alts (see image).
- Navigating away and then back again seems to incur the same load cost/time for each page load.

![image](https://github.com/EVE-University/whctools/assets/173651722/4df42f3f-9dc3-48e9-8f68-c1154e3f90fb)

We probably want to cut down the amount of information this page is dealing with:
- On applications awaiting approval - include the main and the character applying.
  - We only need the data that will help us to make a decision to approve or reject an applicant.
  - We probably do not need to see every single character this player has linked if they are not applying with every single character.
- Cache the skills data into the web client for a short amount of time - like for 15-60 minutes - so that navigating around the module doesn't incur the load cost/time of re-querying all of the skills data when navigating around the module.

**Comment by lynkfox** [comment]
This should be fixed in the current version im working on. The skill checks, instead of being pulled when all the applications are pulled, are only now pulled when the button is pressed

**Comment by lynkfox** [comment]
additionally, there were other small refactors that should increase speed overall throughout the application

**Comment by mome-borogove** [comment]
(v0.2.3) Load speed has been improved a *lot*. It definitely was the skill checks. They're still fairly slow, but outside of the initial re-application period where we'll be accepting a lot of folks back, this probably won't ever be an issue.

Can close this one out.
