### ISSUE TITLE
Resetting rejections not resetting alts

### ISSUE THREAD

**Issue by MImpostor** [EVE-University/whctools#15]
When you reset a main that was rejected for skill reasons, all the alts rejected for skill stay on cooldown. While they can be manually reset, once one toon has skill approval, the rest lacking the skills shouldn't be a blocking reason anymore. It doesn't break anything, CCs can just reset all the alts too, but its unintuitive and requires CCs manually finding all that character's alts an re-enabling them.

Reproduction steps: 
1. Apply on a main with at least one alt
2. Reject the main due to skills
3. Reset main (lets say they inject the skills needed)
4. Apply again on main
5. Accept the main

End result: The alt(s) are on application cooldown for skills while the main is a member.

If you kick someone, reset the main, and approve them, it leads to the same scenario of alts being blocked while a main is in the community, but this seems far more niche and personally I'm okay with resetting that requiring more CC involvement.

We might want it so resetting a main always resets all their alts (or maybe every toon resets all linked toons, although making it main-only means it'd need to be more intentional). I definitely think all linked toons with insufficient skills should be reset when the main is reset for insufficient skills.

Currently, if you reject for other reasons it doesn't reject all linked toons so doesn't need mass-approval to counteract it. I'm struggling to think of a circumstance this would happen in, so I'm not sure if it matters one way or the other.

**Comment by lynkfox** [comment]
Duplicate :)

https://github.com/EVE-University/whctools/issues/12#issue-2368224360

(To be clear the reason for all the alts still being blocked is tied to the rejection rejecting all of them, and fixing one will fix the other
