### ISSUE TITLE
Stale skill check data

### ISSUE THREAD

**Issue by mome-borogove** [EVE-University/whctools#17]
It looks like the skills pulled for the skill check panel are out of date. I just verified that one of my alts does indeed meet all the skills in the skillset, but it's returning a red X. Character is Ara Khaspi (2118610448), for reference.

**Comment by lynkfox** [comment]
Nothing I can do about that directly yet. The skills are pulled from member
audit, and Im not sure what the current update schedule (if at all) is

However, individuals can force an update on any toon that is there's I
believe?

Mmm now I'm not so certain. I know there is a way to trigger it, I'll look
into that

**Comment by mome-borogove** [comment]
Alright, looks like #16 is a dup then. Can close that.

But if member audit is reporting its last update time correctly, then this is a blocker. Most of the updates I see are at least 6 months old. Some characters have never been pulled at all. If there's not a mechanism for member audit to be up to date for relevant characters within some number of hours of an application, we may want to look for an alternative.

**Comment by lynkfox** [comment]
Yeah. There is a way to force the update I just have to figure out the
timing of it

**Comment by Deadevilgrounds** [comment]
Yeah we dont auto pull all the member audit data anymore as it was a huge load on the server when most of the time the data is not used by anyone.
For Intake and Progression we have a button to pull the data for that particular client when requested. So we could implement a simular thing for this app, a button to request updated data only if it shows they don't have the skills. No need to pull it when they do have the skills etc

**Comment by Deadevilgrounds** [comment]
Also when a player adds their character, or re-adds it to member audit it will also pull the latest data.

**Comment by lynkfox** [comment]
@Deadevilgrounds do you happen to have the code handy for that refresh?

**Comment by Deadevilgrounds** [comment]
This is the method used in the hr apps
```
def hr_admin_app_update_memberaudit(request, app_id):
    logger.debug("hr_admin_app_update_memberaudit called for app id %d", app_id)
    app = get_object_or_404(Application, pk=app_id)
    try:
        ma_char = MA_Character.objects.get(eve_character=app.character.eve_character)
    except ObjectDoesNotExist:
        ma_char = None

    if ma_char is not None:
        ma_char.reset_update_section("skills")
        ma_char.reset_update_section("wallet_balance")
        ma_update_character.apply_async(
            kwargs={"character_pk": ma_char.pk, "force_update": True},
            priority=MEMBERTOOLS_TASKS_FOREGROUND_PRIORITY,
        )
    else:
        messages.warning(
            request,
            f"{app.character.character_name} is not registered with Member Audit.",
        )

    return redirect("membertools_admin:view", app.id)
```

**Comment by Deadevilgrounds** [comment]
from memberaudit.tasks import update_character as ma_update_character
