### ISSUE TITLE
Action --> Remove All Characters should have a confirmation dialog

### ISSUE THREAD

**Issue by jpkoester1** [EVE-University/whctools#18]
"Remove all characters" is currently a single click action, even if you misclick all characters will be gone. I would prefer, if there was a confirmation dialog (OK/Cancel) that listed all the characters you were about to remove

**Comment by jpkoester1** [comment]
also when that happens you get a 12 month timeout 
![image](https://github.com/EVE-University/whctools/assets/66028066/f8087138-23cc-4b72-b9e3-f77d3606ea84)

**Comment by lynkfox** [comment]
remove all characters and kick alt (under the expansion of a character on the acl list) both have confirmation dialogues in the branch im currently working in

click OK on the confirmation also returns you to the same page.
