### ISSUE TITLE
Rejected Applications --> Reset bounces you back to the "Applications Awaiting Approval" page

### ISSUE THREAD

**Issue by jpkoester1** [EVE-University/whctools#19]
when clicking the Reset button on the "Rejected Applications" page you get bounced over to the Applications Awaiting Approval page. Can we get it so the Rejected Applications tab stays active so you can reset the next character immediately

**Comment by lynkfox** [comment]
This is already corrected in the current version I'm working on.

**Comment by mome-borogove** [comment]
(v0.2.3) Confirm fixed. Can close this out.
