### ISSUE TITLE
Multiple clicks on 'check skills' queue

### ISSUE THREAD

**Issue by mome-borogove** [EVE-University/whctools#25]
Low priority, but will probably bite someone impatient at some point.

If you click the 'check skills' button several times, it will send multiple requests to check those skills. This sounds a bit silly, but the check skills interface takes a while and there's no indication that it's in progress, so if someone impatient believes the UI is lagging, clicking again isn't unusual. Unfortunately, these events queue. So, for instance, if you click the button several times, wait for the skills dialog to pop up, then close it, new skills dialog boxes will continue to pop up later without further interaction. This can go on for minutes if you click an unreasonable number of times.

I suppose I'm also a bit concerned that those are direct ESI requests. If so, I'd hate to get the Auth server rate-limited because of someone's impatience.

**Comment by lynkfox** [comment]
they are not direct ESI requests, its entirely internal. Upcoming refresh skills will be a button on the skills pane, and that will probably have a timer on it (ie can only be done once per 6 hours or something)
