### ISSUE TITLE
Open application alliance information is incorrect

### ISSUE THREAD

**Issue by mome-borogove** [EVE-University/whctools#40]
I strongly suspect this is a side-effect of #17, but on the Staff: Applications Awaiting Approval page, the alliance listed for characters is incorrect.

This is a bit odd, since I have an alt which, on the user applications page, says "Character is not in IVY or IVY-A, and cannot apply." but on the Applications Awaiting Approval page, it says the alliance is Ivy League.

To be clear, this is a bizarre situation where my alt had an open application before the most recent update, so they bypassed the normal restriction from the user page. Which is why I can see both simultaneously. That part is not a problem, because it can't happen when we launch. It's just happens to be an easy case where I can see the information skew.

**Comment by lynkfox** [comment]
Oh, I forgot to tell Bates the settings got moved into the proper location
for those so probably need to be added to the startup scripts

**Comment by mome-borogove** [comment]
This is the same as #54, fixed by #55 .
