### ISSUE TITLE
Stale check for alt alliance status

### ISSUE THREAD

**Issue by mome-borogove** [EVE-University/whctools#46]
Currently, the only mechanism for asserting that a character is in or not in the correct alliance is via a check in the [index view](https://github.com/EVE-University/whctools/blob/f4df412dcd91c6a6ee1d81690138e432ebd94f70/whctools/views.py#L122). This data is stale, as there's no mechanism to update MA prior to an application.

This has two problems:
(1) Characters that have recently joined either alliance will incorrectly be unable to apply as an alt to WHC
(2) Characters that have recently left either alliance will incorrectly be able to apply as an alt to WHC

Both need to get fixed.

In order to avoid ESI spam, I suspect the correct answer here is to move the check to the actual application step (`apply` not `index`) and---if the character is not in an approved alliance---trigger an ESI character detail pull to update the character and check again. Only then reject for being in the wrong alliance. This should be a small number of triggers, and (assuming people are not being dumb) would be required every time anyways. (And if a small number of people *are* being dumb, it's still limited to once every `WHCTOOLS_TRANSIENT_REJECT` hours, so it really can't cause major problems.)

**Comment by mome-borogove** [comment]
This is a bit worse than I thought, because some of the alts that older folks have can be *very* out of date, and we really don't want to be accepting alts out of alliance.

**Comment by mome-borogove** [comment]
So I've taken a longer look at this. I see no way to solve this without an ESI pull on every application. There's just no way to get it right. Take a simple example: someone's alt sets up their own corp outside of IVY-A. There's currently no MA update trigger, so that character is listed as still part of IVY-A. That character applies. We see an IVY-A applicant and accept it. That out of alliance character is now added to the ACL. In this scenario, it's impossible to distinguish this alt from another alt who *didn't* set up their own corp without an ESI update.

The reality is: we must have a way of ensuring every single applicant is in the right corp/alliance at the time of the application. The skill check is okay to skip for alts that have a valid skilled-checked main, but not the corp/alliance check. This means an ESI pull on every application.

With MA v3+, we could reduce the ESI calls by a factor of about 10x by using fine-granularity character fetches, but at this point, it's a question of how we get accurate character data, not if.

**Comment by lynkfox** [comment]
Unfortunately I think you're right, so I'll leave it up to Bates and Marn
about stress on the system

**Comment by mome-borogove** [comment]
Per Marn, the corp/alliance checks we're using are updated regularly outside of MA, so this is all a non-issue with some simple checks (which are now in PR #42.

**Comment by mome-borogove** [comment]
Fixed in #42.
