### ISSUE TITLE
No Main Character available

### ISSUE THREAD

**Issue by mome-borogove** [EVE-University/whctools#5]
This might be a database desync problem, as my characters were applied and accepted before the most recent update, but the app is currently not recognizing my main character as such in the applicant-side of things. It's giving me a "Main character has not applied yet - please apply on Main first!" on my main character and every other alt I have listed.

**Comment by SirFinnbar** [comment]
I am also experiencing this error and I had not applied nor been accepted before.

**Comment by lynkfox** [comment]
Awesome 👍 I'm guessing it's a difference between 3.0 and 4.0. I'll look
into it this weekend

**Comment by lynkfox** [comment]
bugfix included in PR https://github.com/EVE-University/whctools/pull/7
