### ISSUE TITLE
Application lists IVY-A characters as part of IVY

### ISSUE THREAD

**Issue by MImpostor** [EVE-University/whctools#54]
On the "Staff: Applications Awaiting Approval" tab, every character has "A: _**Ivy League**_" below them, even if they're part of the alt alliance. This might just be a truncation issue which isn't very big (although it makes the alliance field kinda useless), but I'm reporting it in case there is some deeper underlying issue causing it. "Staff: WHC ACL" gives the correct corporation and alliance for the alts once someone is accepted.

Steps to reproduce: 
1) Have alt alliance character apply to join
2) As someone with permissions to accept members, look at application. The character column says "A: _**Ivy League**_"

**Comment by mome-borogove** [comment]
Thanks for bringing this up. I'd seen this before but totally forgotten to correct it.
