### ISSUE TITLE
[Request] ACL list text export

### ISSUE THREAD

**Issue by mome-borogove** [EVE-University/whctools#6]
As a stopgap for Auth/in-game ACL deltas, can we get a text dump of the expected ACL? It'd be a *lot* easier than scraping the page. Format doesn't matter that much (a consistent delimiter would be nice, I suppose), nor does the info besides the character name (but you're welcome to dump everything, too).

**Comment by lynkfox** [comment]
feature added in https://github.com/EVE-University/whctools/pull/7
